version: '3.2'
services:
  openmole:
    build:
      context: .
      dockerfile: Dockerfile
      args :
        UID: 0
        GID: 0
    image: openmole/openmole:8.0-SNAPSHOT
    ports:
      - target: 8443
        published: 8080
    volumes:
      - /root/openMole_workSpace:/home/mole/workspace

