version: '3.7'
services:
  openmole:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "openmole"
    environment:
      - MEM=8G
    image: openmole/openmole
    ports:
      - target: 8443
        published: ${PORT}
    volumes:
      - data:/home/mole/workspace

volumes:
  data:
    name: ${VOLNAME}