#!/bin/bash

docker build --tag openmole-build:latest .

while [[ $# -gt 1 ]]; do
  key="$1"

  case $key in
      -v|--volume)
      VOLUME="$2"
      shift # past argument
      ;;
      *)
      # unknown option
      ;;
  esac
  shift # past argument or value
done


OPTIONS="-e JAVA_OPTS=-Dsbt.ivy.home=/sources/.ivy2/ -e HOME=/sources/"

docker_run="docker run -it -u $(id -u) $OPTIONS"

if [[ $VOLUME != "" ]]; then
  mkdir -p "$VOLUME"
  "${docker_run}" -v "$VOLUME:/sources/" openmole-build /bin/bash
else  "${docker_run}" openmole-build /bin/bash
fi

